# Generated by Django 3.1.7 on 2021-03-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
