# Generated by Django 3.1.6 on 2021-02-14 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avg_price', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='offers',
            name='active',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='active',
        ),
        migrations.AlterField(
            model_name='offers',
            name='type',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Actives',
        ),
        migrations.DeleteModel(
            name='OffersType',
        ),
        migrations.DeleteModel(
            name='TypeActives',
        ),
        migrations.AddField(
            model_name='offers',
            name='stock',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.stocks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stock',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.stocks'),
            preserve_default=False,
        ),
    ]
