# Generated by Django 3.1.7 on 2021-03-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_portfolio_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='closed',
        ),
    ]
