# Generated by Django 3.1.7 on 2021-04-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debt',
            field=models.FloatField(default=0),
        ),
    ]
