# Generated by Django 3.1.7 on 2021-03-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_order_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
