# Generated by Django 3.1.7 on 2021-03-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210327_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_closed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
