# Generated by Django 3.1.7 on 2021-04-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quotes'),
        ('main', '0005_order_date_closed'),
    ]

    operations = [
    ]
