# Generated by Django 3.1.7 on 2021-04-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_date_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_debt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='short_balance',
            field=models.FloatField(default=-100000),
        ),
    ]
