# Generated by Django 3.1.6 on 2021-02-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210227_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='avg_price',
        ),
    ]
