# Generated by Django 3.1.6 on 2021-03-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_stocks_avg_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
    ]
