# Generated by Django 3.1.7 on 2021-04-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20210403_0804'),
        ('main', '0006_auto_20210401_2224'),
    ]

    operations = [
    ]
