# Generated by Django 3.1.7 on 2021-04-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20210403_1744'),
        ('main', '0005_auto_20210402_2358'),
    ]

    operations = [
    ]
