# Generated by Django 3.1.6 on 2021-03-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210302_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=100000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
