# Generated by Django 3.1.7 on 2021-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210419_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/preset.jpg', max_length=255, null=True, upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
