# Generated by Django 3.1.7 on 2021-04-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210419_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='index',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocks',
            name='description',
            field=models.TextField(),
        ),
    ]
