# Generated by Django 3.1.7 on 2021-04-09 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_candles'),
    ]

    operations = [
        migrations.AddField(
            model_name='candles',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.stocks'),
            preserve_default=False,
        ),
    ]
