# Generated by Django 3.1.7 on 2021-05-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210424_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
