# Generated by Django 3.1.6 on 2021-03-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210305_0020'),
        ('main', '0009_auto_20210304_1413'),
        ('main', '0007_auto_20210305_0025'),
    ]

    operations = [
    ]
