# Generated by Django 3.1.6 on 2021-03-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20210305_2335'),
        ('main', '0010_merge_20210305_2216'),
    ]

    operations = [
    ]
