# Generated by Django 3.1.7 on 2021-04-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210408_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
