# Generated by Django 3.1.6 on 2021-03-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20210306_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='avatar',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
