# Generated by Django 3.1.7 on 2021-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_statistics_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='user_active',
            field=models.IntegerField(default=0),
        ),
    ]
