# Generated by Django 3.1.7 on 2021-04-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_images'),
        ('main', '0010_candles_stock'),
    ]

    operations = [
    ]
