# Generated by Django 3.1.7 on 2021-04-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_20210416_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_debt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='short_balance',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_debt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='short_balance',
            field=models.FloatField(default=-100000),
        ),
    ]
