# Generated by Django 3.1.7 on 2021-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_statistics_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='count_stocks',
            field=models.IntegerField(default=0),
        ),
    ]
