# Generated by Django 3.1.7 on 2021-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210313_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=None),
        ),
    ]
