# Generated by Django 3.1.7 on 2021-05-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_statistics_count_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='count_long',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='count_short',
            field=models.IntegerField(default=0),
        ),
    ]
