# Generated by Django 3.1.7 on 2021-05-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210511_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='max_balance',
            field=models.IntegerField(default=0),
        ),
    ]
