# Generated by Django 3.1.7 on 2021-03-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210317_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
