# Generated by Django 3.1.7 on 2021-05-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_statistics_max_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='the_richest',
            field=models.CharField(default='', max_length=255),
        ),
    ]
