# Generated by Django 3.1.7 on 2021-05-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_statistics_the_richest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('data', models.JSONField()),
                ('stock', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='main.stocks')),
            ],
        ),
    ]
