# Generated by Django 3.1.7 on 2021-05-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_stocks_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
