# Generated by Django 3.1.7 on 2021-05-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_cryptocurrencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencies',
            name='price',
            field=models.CharField(default='', max_length=255),
        ),
    ]
