# Generated by Django 3.1.7 on 2021-05-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210515_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
