# Generated by Django 3.1.7 on 2021-05-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='aver_price',
            field=models.IntegerField(default=0),
        ),
    ]
