# Generated by Django 3.1.7 on 2021-05-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_portfolio_aver_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='aver_price',
            field=models.FloatField(default=0),
        ),
    ]
