# Generated by Django 3.1.7 on 2021-06-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210524_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='line',
            field=models.IntegerField(default=-1),
        ),
    ]
