# Generated by Django 3.1.7 on 2021-06-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_quotes_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='candles',
            name='seconds_left',
            field=models.IntegerField(default=0)
        ),
    ]
