# Generated by Django 3.1.7 on 2021-06-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210616_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='name',
        ),
    ]
