# Generated by Django 3.1.7 on 2021-06-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_statistics_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandlesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars\\preset.jpg', max_length=255, null=True, upload_to='avatars'),
        ),
    ]
