# Generated by Django 3.1.7 on 2021-06-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210626_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/preset.jpg', max_length=255, null=True, upload_to='avatars'),
        ),
    ]
